
spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: todomatic

  jackson:
    deserialization:
      adjust-dates-to-context-time-zone: false
    time-zone: America/Fortaleza

  datasource:
    url: ${DS_URL}
    driver-class-name: ${DS_DRIVER_CLASS_NAME}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate.ddl-auto: update